### ISSUE TITLE
Run benchmarks from main branch for new projects

### ISSUE THREAD

**Issue by art-w** [ocurrent/current-bench#354]
When onboarding a new project, the benchmarks do not immediately run on the main/master branch (you have to create PRs). It would be a nicer feedback that everything is working properly if they would! (also to establish a baseline for PRs)

**Comment by gs0510** [comment]
The benchmarks do immediately run on the default branch, I have this demo repo here: and the corresponding autumn page here (https://autumn.ocamllabs.io/gs0510/test-bench-bootstrap?worker=autumn&image=ocaml%2Fopam%3Adebian-11-ocaml-4.13). The only consideration is that the default branch needs to have the `make` target and the right format of the benchmarks otherwise it will fail!
